### ISSUE TITLE
Add ELK stack

### ISSUE THREAD

**Issue by mdarby** [getcarina/carina-oauth#1]
Remove Papertrail as well.

**Comment by everett-toews** [comment]
Could this use our existing ObjectRocket ElasticSearch and Kibana?

**Comment by everett-toews** [comment]
@smashwilson Would it make sense to roll this into our existing ObjectRocket ElasticSearch and Kibana?

**Comment by smashwilson** [comment]
Indeed it would! You should have already access to the production Elasticsearch hosts, username, and password in your [`credentials.yml` for Nexus](https://github.com/rackerlabs/devex-ops/blob/master/nexus/prerequisites.md#passwords). You can also pull the HTTPS connect string directly from ObjectRocket - the OR account is with the rest of our passwords and it's the "deconst_es_production" cluster.

We'll also need to add ACLs for your originating IPs (your public IPs, I think, I believe the ES cluster is in DFW so we can't use servicenet). You can do that on the ObjectRocket dashboard.

After that, you'll write a logstash config, run a logstash container, and point your oauth container(s) at it with `--log-driver` options.

For the Carina control panel we're adding a "source" field in logstash:

```
input {
  syslog {
    port => 5514
    add_field => {
      "source" => "carina_control_panel"
    }
  }
}
```

You'll probably want to do something similar so we can easily narrow searches to find oauth issues.

**Comment by mdarby** [comment]
Seems a passphrase is needed? Also I've logged into the place for our passwords and I'm not linked to any Nexus-centric projects...

![deconst-nexus 2016-03-07 10-29-17](https://cloud.githubusercontent.com/assets/2805/13573961/1549c966-e450-11e5-8b2c-c19143338c4e.png)

**Comment by smashwilson** [comment]
Ah, I just added you to the project. Give it another shot.

**Comment by mdarby** [comment]
https://github.com/getcarina/carina-oauth/pull/5
